version: '2'
services:
  sdz-agent:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DOCKER=true
      - CLIENT_ID=
      - CLIENT_SECRET=
      - ISSUER_URL=https://api-prod.seedz.ag/auth/oidc/.well-known/openid-configuration
      - WS_SERVER_URL=wss://api-prod.seedz.ag
