version: '2'
services:
  sdz-agent:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DOCKER=true
      - API_URL=
      - FTP_HOST=
      - FTP_PASSWORD=
      - FTP_PORT=
      - FTP_USERNAME=
      - IDENTITY_DATABASE=
      - MONGO_URL=
      - ISSUER_URL=
