trigger:
  branches:
    include:
    - main

pr:
  branches:
    exclude:
    - main

resources:
  repositories:
  - repository: template
    type: git
    name: Platform Engineering/templates-pipeline
    ref: master

extends:
  template: build-ecr/github/seedz-ag/sdz-agent.yaml@template
