trigger:
  branches:
    include:
    - main

pr:
  branches:
    exclude:
    - main

resources:
  repositories:
  - repository: template
    type: git
    name: Platform Engineering/templates-pipeline
    ref: master

variables:
- group: sdz-agent

extends:
  template: build-ecr/github/seedz-ag/pipeline.yaml@template
  parameters:
    AWS_ACC_ID: $(AWS_ACC_ID)
    REPOSITORY_NAME: $(REPOSITORY_NAME)
    SNYK_ORG: $(SNYK_ORG)
