trigger:
  branches:
    include:
      - main
resources:
  repositories:
    - repository: template
      type: git
      name: Platform Engineering/templates-pipeline
      ref: master
variables:
  - group: sdz-agent-v2
extends:
  template: ecs/fargate/seedz-integration/nodejs/agent-saas.yaml@template
