trigger:
  - feature/superacao

resources:
  repositories:
    - repository: template
      type: git
      name: Devops/pipeline-templates
      ref: v2

variables:
  - name: SERVICE_NAME
    value: 'sdz-age-superacao'

extends:
  template: node/node.github.generic.v1.yml@template
  parameters:
    SERVICENAME: ${{ variables.SERVICE_NAME }}
