[program:sdz-agent]
directory=/opt/sdz-agent/
command=/opt/sdz-agent/bin/run -S
user=root
environment=
	INFORMIXDIR=/opt/sdz-agent/node_modules/informixdb/installer/onedb-odbc-driver/
    LD_LIBRARY_PATH=/sdz-agent/node_modules/sdz-agent-database-oracle/instantclient_21_3
stderr_logfile=/opt/sdz-agent/err.log
stdout_logfile=/opt/sdz-agent/dout.log