name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      token: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: 12.22.10

      - name: set env.version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: create new branch
        run: git checkout -b ${{ env.version }}

      - name: push new branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git push --set-upstream origin ${{ env.version }}
