name: Release

on:
  push:
    branches:
      - master-fake

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Deps
        run: npm i --ignore-scripts

      - name: Semantic Release
        run: npx semantic-release --ci
